### ISSUE TITLE
Suggestion: Existing Blendshapes

### ISSUE THREAD

**Issue by Talamis** [Adjerry91/VRCFaceTracking-blender-plugin#2]
Recocnize Existing Blendshapes and automaticly Select or Search in select window if possible
Overwrite Existing Empty Blendshapes if possible

**Comment by Adjerry91** [comment]
This is definitely what I want to work for the end product! I just still trying to figure out how get that setup.

**Comment by Adjerry91** [comment]
I can add the shape key condition to look for existing shape keys on the creation table and perform an overwrite.

**Comment by Adjerry91** [comment]
Overwrite existing shape keys enhancement is now available on v0.4.0. Any assigned to the 'Basis' layer will perform no operations.

**Comment by Adjerry91** [comment]
Version v1.0.1 now has dropdown box for shape keys on the mesh
